name: stockprice-infra/svc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  TF_VERSION: 1.7.0

jobs:
  Cluster_Creation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Set up SSH key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/kubectl-key.pem
         chmod 600 ~/.ssh/kubectl-key.pem

      - name: SSH into kubectl-node and apply infra-svc
        run: |
          set -e
          KUBECTL_HOST=$(terraform output -raw kubectl_public_ip)
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/kubectl-key.pem ec2-user@$KUBECTL_HOST << 'EOF'
            set -e
            cd ~
            if [ ! -d "stockprice-infra-svc" ]; then
              git clone https://github.com/uthmanakz/stockprice-infra-svc.git
            else
              cd stockprice-infra-svc
              git pull
              cd ..
            fi
            cd stockprice-infra-svc
            terraform init -input=false
            terraform apply -auto-approve
            EOF



